package education.dao;

import education.entity.Chapter;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ChapterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer chapterid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter
     *
     * @mbggenerated
     */
    int insert(Chapter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter
     *
     * @mbggenerated
     */
    int insertSelective(Chapter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter
     *
     * @mbggenerated
     */
    Chapter selectByPrimaryKey(Integer chapterid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Chapter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Chapter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Chapter record);

  Chapter findChapterByID(Integer chapterID);

  int addChapter(@Param("courseID") Integer courseID, @Param("name") String name, @Param("description") String description);

  int updateChapter(@Param("chapterID") Integer chapterID, @Param("name") String name, @Param("description") String description);

  List<Integer> findKnowledgeIDByID(Integer chapterID);


}
