package education.dao;

import education.entity.Chapter;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import java.util.List;

public interface ChapterMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table chapter
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(Integer chapterid);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table chapter
   *
   * @mbggenerated
   */
  int insert(Chapter record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table chapter
   *
   * @mbggenerated
   */
  int insertSelective(Chapter record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table chapter
   *
   * @mbggenerated
   */
  Chapter selectByPrimaryKey(Integer chapterid);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table chapter
   *
   * @mbggenerated
   */
  int updateByPrimaryKeySelective(Chapter record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table chapter
   *
   * @mbggenerated
   */
  int updateByPrimaryKeyWithBLOBs(Chapter record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table chapter
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(Chapter record);

  @Select("select * from chapter where chapterID = #{chapterID}")
  Chapter findChapterByID(Integer chapterID);

  @Insert("insert into chapter values (#{courseID}, #{name}, #{description})")
  int addChapter(@Param("courseID") Integer courseID, @Param("name") String name, @Param("description") String description);

  @Update("update chapter set name = #{name}, description = #{description} where chapterID = #{chapterID}")
  int updateChapter(@Param("chapterID") Integer chapterID, @Param("name") String name, @Param("description") String description);

  @Select("select kpID from knowledgepoint where chapterID = #{chapterID}")
  List<Integer> findKnowledgeIDByID(Integer chapterID);


}
