package education.dao;

import education.entity.ChooseCourseKey;

public interface ChooseCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choosecourse
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(ChooseCourseKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choosecourse
     *
     * @mbggenerated
     */
    int insert(ChooseCourseKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choosecourse
     *
     * @mbggenerated
     */
    int insertSelective(ChooseCourseKey record);
}