package education.dao;

import education.entity.ChooseCourse;
import education.entity.ChooseCourseKey;

public interface ChooseCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choosecourse
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(ChooseCourseKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choosecourse
     *
     * @mbggenerated
     */
    int insert(ChooseCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choosecourse
     *
     * @mbggenerated
     */
    int insertSelective(ChooseCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choosecourse
     *
     * @mbggenerated
     */
    ChooseCourse selectByPrimaryKey(ChooseCourseKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choosecourse
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ChooseCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choosecourse
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ChooseCourse record);
}