package education.dao;

import education.entity.Course;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CourseMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table course
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(Integer courseid);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table course
   *
   * @mbggenerated
   */
  int insert(Course record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table course
   *
   * @mbggenerated
   */
  int insertSelective(Course record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table course
   *
   * @mbggenerated
   */
  Course selectByPrimaryKey(Integer courseid);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table course
   *
   * @mbggenerated
   */
  int updateByPrimaryKeySelective(Course record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table course
   *
   * @mbggenerated
   */
  int updateByPrimaryKeyWithBLOBs(Course record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table course
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(Course record);

  Course findCourseByID(Integer courseID);

  List<Integer> findChapterIDByID(Integer courseID);

  int addCourse(@Param("teacherID") Integer teacherID, @Param("courseName") String courseName, @Param("description") String description);

  int updateCourse(@Param("courseID") Integer courseID, @Param("courseName") String courseName, @Param("description") String description);


}
