package education.dao;

import education.entity.DoPaper;
import education.entity.DoPaperKey;

public interface DoPaperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dopaper
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(DoPaperKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dopaper
     *
     * @mbggenerated
     */
    int insert(DoPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dopaper
     *
     * @mbggenerated
     */
    int insertSelective(DoPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dopaper
     *
     * @mbggenerated
     */
    DoPaper selectByPrimaryKey(DoPaperKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dopaper
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DoPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dopaper
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DoPaper record);
}