package education.dao;

import education.entity.Exercise;
import education.entity.ExerciseWithBLOBs;

public interface ExerciseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer exerciseid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbggenerated
     */
    int insert(ExerciseWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbggenerated
     */
    int insertSelective(ExerciseWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbggenerated
     */
    ExerciseWithBLOBs selectByPrimaryKey(Integer exerciseid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ExerciseWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(ExerciseWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Exercise record);
}