package education.dao;

import education.entity.FavoriteKey;

public interface FavoriteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(FavoriteKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbggenerated
     */
    int insert(FavoriteKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbggenerated
     */
    int insertSelective(FavoriteKey record);
}