package education.dao;

import education.entity.KnowledgePoint;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface KnowledgePointMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledgepoint
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer kpid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledgepoint
     *
     * @mbggenerated
     */
    int insert(KnowledgePoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledgepoint
     *
     * @mbggenerated
     */
    int insertSelective(KnowledgePoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledgepoint
     *
     * @mbggenerated
     */
    KnowledgePoint selectByPrimaryKey(Integer kpid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledgepoint
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(KnowledgePoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledgepoint
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(KnowledgePoint record);

    KnowledgePoint findKnowledgeByID(Integer kpID);

    List<Integer> findDetailByID(Integer knowledgeID);

  int addKnowledge(@Param("chapterID") Integer chapterID,@Param("name") String knowledgeName);

  int updateKnowledge(@Param("kpID") Integer knowledgeID,@Param("name") String knowledgeName);
}
