package education.dao;

import education.entity.KPDetail;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface KPDetailMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table kpdetail
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table kpdetail
   *
   * @mbggenerated
   */
  int insert(KPDetail record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table kpdetail
   *
   * @mbggenerated
   */
  int insertSelective(KPDetail record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table kpdetail
   *
   * @mbggenerated
   */
  KPDetail selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table kpdetail
   *
   * @mbggenerated
   */
  int updateByPrimaryKeySelective(KPDetail record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table kpdetail
   *
   * @mbggenerated
   */
  int updateByPrimaryKeyWithBLOBs(KPDetail record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table kpdetail
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(KPDetail record);

  KPDetail findDetailByID(Integer detailID);

  int addDetail(@Param("kpID") Integer kpID, @Param("description") String description);

  int updateDetail(@Param("id") Integer detailID, @Param("description") String description);
}
