package education.dao;

import education.entity.KPDetail;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import java.util.List;

public interface KPDetailMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table kpdetail
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table kpdetail
   *
   * @mbggenerated
   */
  int insert(KPDetail record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table kpdetail
   *
   * @mbggenerated
   */
  int insertSelective(KPDetail record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table kpdetail
   *
   * @mbggenerated
   */
  KPDetail selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table kpdetail
   *
   * @mbggenerated
   */
  int updateByPrimaryKeySelective(KPDetail record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table kpdetail
   *
   * @mbggenerated
   */
  int updateByPrimaryKeyWithBLOBs(KPDetail record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table kpdetail
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(KPDetail record);

  //通过detailID获取一个具体的kpdetail 项
  @Select("select * from kpdetail where id = #{detailID}")
  KPDetail findDetailByID(Integer detailID);

  //添加一条记录
  @Insert("insert into kpdetail (kpID, description)values (#{kpID}, #{description})")
  int addDetail(@Param("kpID") Integer kpID, @Param("description") String description);

  //更新一条记录
  @Update("update kpdetail set description = #{description} where id = #{id}")
  int updateDetail(@Param("id") Integer detailID, @Param("description") String description);
}
