package education.dao;

import education.entity.Memo;

public interface MemoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer memoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memo
     *
     * @mbggenerated
     */
    int insert(Memo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memo
     *
     * @mbggenerated
     */
    int insertSelective(Memo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memo
     *
     * @mbggenerated
     */
    Memo selectByPrimaryKey(Integer memoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Memo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Memo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Memo record);
}