#Dedault configuration
spring:
  profiles:
    active: dev

#MapperLocations /src/main/resources
mybatis:
  typeAliasesPackage: com.anxin.education.entity
  mapperLocations: classpath:mapping/*.xml


---

#Development configuration
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://localhost:3306/education?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: mysql2018
    driver-class-name: com.mysql.cj.jdbc.Driver

    # use druid Datasource
    type: com.alibaba.druid.pool.DruidDataSource

