package education.entity;

public class Chapter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.chapterID
     *
     * @mbggenerated
     */
    private Integer chapterid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.courseID
     *
     * @mbggenerated
     */
    private Integer courseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.chapterID
     *
     * @return the value of chapter.chapterID
     *
     * @mbggenerated
     */
    public Integer getChapterid() {
        return chapterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.chapterID
     *
     * @param chapterid the value for chapter.chapterID
     *
     * @mbggenerated
     */
    public void setChapterid(Integer chapterid) {
        this.chapterid = chapterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.courseID
     *
     * @return the value of chapter.courseID
     *
     * @mbggenerated
     */
    public Integer getCourseid() {
        return courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.courseID
     *
     * @param courseid the value for chapter.courseID
     *
     * @mbggenerated
     */
    public void setCourseid(Integer courseid) {
        this.courseid = courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.name
     *
     * @return the value of chapter.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.name
     *
     * @param name the value for chapter.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.description
     *
     * @return the value of chapter.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.description
     *
     * @param description the value for chapter.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}