package education.entity;

public class ChooseCourseKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choosecourse.studentID
     *
     * @mbggenerated
     */
    private String studentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choosecourse.courseID
     *
     * @mbggenerated
     */
    private Integer courseid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choosecourse.studentID
     *
     * @return the value of choosecourse.studentID
     *
     * @mbggenerated
     */
    public String getStudentid() {
        return studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choosecourse.studentID
     *
     * @param studentid the value for choosecourse.studentID
     *
     * @mbggenerated
     */
    public void setStudentid(String studentid) {
        this.studentid = studentid == null ? null : studentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choosecourse.courseID
     *
     * @return the value of choosecourse.courseID
     *
     * @mbggenerated
     */
    public Integer getCourseid() {
        return courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choosecourse.courseID
     *
     * @param courseid the value for choosecourse.courseID
     *
     * @mbggenerated
     */
    public void setCourseid(Integer courseid) {
        this.courseid = courseid;
    }
}