package education.entity;

public class ChooseCourse extends ChooseCourseKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choosecourse.progressID
     *
     * @mbggenerated
     */
    private Integer progressid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choosecourse.progressID
     *
     * @return the value of choosecourse.progressID
     *
     * @mbggenerated
     */
    public Integer getProgressid() {
        return progressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choosecourse.progressID
     *
     * @param progressid the value for choosecourse.progressID
     *
     * @mbggenerated
     */
    public void setProgressid(Integer progressid) {
        this.progressid = progressid;
    }
}