package education.entity;

public class Course {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.courseID
     *
     * @mbggenerated
     */
    private Integer courseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.courseName
     *
     * @mbggenerated
     */
    private String coursename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.teacherID
     *
     * @mbggenerated
     */
    private Integer teacherid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.courseID
     *
     * @return the value of course.courseID
     *
     * @mbggenerated
     */
    public Integer getCourseid() {
        return courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.courseID
     *
     * @param courseid the value for course.courseID
     *
     * @mbggenerated
     */
    public void setCourseid(Integer courseid) {
        this.courseid = courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.courseName
     *
     * @return the value of course.courseName
     *
     * @mbggenerated
     */
    public String getCoursename() {
        return coursename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.courseName
     *
     * @param coursename the value for course.courseName
     *
     * @mbggenerated
     */
    public void setCoursename(String coursename) {
        this.coursename = coursename == null ? null : coursename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.teacherID
     *
     * @return the value of course.teacherID
     *
     * @mbggenerated
     */
    public Integer getTeacherid() {
        return teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.teacherID
     *
     * @param teacherid the value for course.teacherID
     *
     * @mbggenerated
     */
    public void setTeacherid(Integer teacherid) {
        this.teacherid = teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.description
     *
     * @return the value of course.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.description
     *
     * @param description the value for course.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}