package education.entity;

public class DoPaper extends DoPaperKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dopaper.choose
     *
     * @mbggenerated
     */
    private String choose;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dopaper.choose
     *
     * @return the value of dopaper.choose
     *
     * @mbggenerated
     */
    public String getChoose() {
        return choose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dopaper.choose
     *
     * @param choose the value for dopaper.choose
     *
     * @mbggenerated
     */
    public void setChoose(String choose) {
        this.choose = choose == null ? null : choose.trim();
    }
}