package education.entity;

public class Exercise {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise.exerciseID
     *
     * @mbggenerated
     */
    private Integer exerciseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise.correctOption
     *
     * @mbggenerated
     */
    private String correctoption;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise.teacherID
     *
     * @mbggenerated
     */
    private Integer teacherid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise.exerciseID
     *
     * @return the value of exercise.exerciseID
     *
     * @mbggenerated
     */
    public Integer getExerciseid() {
        return exerciseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise.exerciseID
     *
     * @param exerciseid the value for exercise.exerciseID
     *
     * @mbggenerated
     */
    public void setExerciseid(Integer exerciseid) {
        this.exerciseid = exerciseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise.correctOption
     *
     * @return the value of exercise.correctOption
     *
     * @mbggenerated
     */
    public String getCorrectoption() {
        return correctoption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise.correctOption
     *
     * @param correctoption the value for exercise.correctOption
     *
     * @mbggenerated
     */
    public void setCorrectoption(String correctoption) {
        this.correctoption = correctoption == null ? null : correctoption.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise.teacherID
     *
     * @return the value of exercise.teacherID
     *
     * @mbggenerated
     */
    public Integer getTeacherid() {
        return teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise.teacherID
     *
     * @param teacherid the value for exercise.teacherID
     *
     * @mbggenerated
     */
    public void setTeacherid(Integer teacherid) {
        this.teacherid = teacherid;
    }
}