package education.entity;

public class Favorite extends FavoriteKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorite.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.description
     *
     * @return the value of favorite.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.description
     *
     * @param description the value for favorite.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}