package education.entity;

public class KnowledgePoint {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledgepoint.kpID
     *
     * @mbggenerated
     */
    private Integer kpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledgepoint.chapterID
     *
     * @mbggenerated
     */
    private Integer chapterid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledgepoint.details
     *
     * @mbggenerated
     */
    private String details;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledgepoint.kpID
     *
     * @return the value of knowledgepoint.kpID
     *
     * @mbggenerated
     */
    public Integer getKpid() {
        return kpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledgepoint.kpID
     *
     * @param kpid the value for knowledgepoint.kpID
     *
     * @mbggenerated
     */
    public void setKpid(Integer kpid) {
        this.kpid = kpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledgepoint.chapterID
     *
     * @return the value of knowledgepoint.chapterID
     *
     * @mbggenerated
     */
    public Integer getChapterid() {
        return chapterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledgepoint.chapterID
     *
     * @param chapterid the value for knowledgepoint.chapterID
     *
     * @mbggenerated
     */
    public void setChapterid(Integer chapterid) {
        this.chapterid = chapterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledgepoint.details
     *
     * @return the value of knowledgepoint.details
     *
     * @mbggenerated
     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledgepoint.details
     *
     * @param details the value for knowledgepoint.details
     *
     * @mbggenerated
     */
    public void setDetails(String details) {
        this.details = details == null ? null : details.trim();
    }
}