package education.entity;

public class KnowledgePoint {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledgepoint.kpID
     *
     * @mbggenerated
     */
    private Integer kpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledgepoint.chapterID
     *
     * @mbggenerated
     */
    private Integer chapterid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledgepoint.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledgepoint.kpID
     *
     * @return the value of knowledgepoint.kpID
     *
     * @mbggenerated
     */
    public Integer getKpid() {
        return kpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledgepoint.kpID
     *
     * @param kpid the value for knowledgepoint.kpID
     *
     * @mbggenerated
     */
    public void setKpid(Integer kpid) {
        this.kpid = kpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledgepoint.chapterID
     *
     * @return the value of knowledgepoint.chapterID
     *
     * @mbggenerated
     */
    public Integer getChapterid() {
        return chapterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledgepoint.chapterID
     *
     * @param chapterid the value for knowledgepoint.chapterID
     *
     * @mbggenerated
     */
    public void setChapterid(Integer chapterid) {
        this.chapterid = chapterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledgepoint.name
     *
     * @return the value of knowledgepoint.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledgepoint.name
     *
     * @param name the value for knowledgepoint.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}