package education.entity;

public class KPDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kpdetail.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kpdetail.kpID
     *
     * @mbggenerated
     */
    private Integer kpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kpdetail.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kpdetail.id
     *
     * @return the value of kpdetail.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kpdetail.id
     *
     * @param id the value for kpdetail.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kpdetail.kpID
     *
     * @return the value of kpdetail.kpID
     *
     * @mbggenerated
     */
    public Integer getKpid() {
        return kpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kpdetail.kpID
     *
     * @param kpid the value for kpdetail.kpID
     *
     * @mbggenerated
     */
    public void setKpid(Integer kpid) {
        this.kpid = kpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kpdetail.description
     *
     * @return the value of kpdetail.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kpdetail.description
     *
     * @param description the value for kpdetail.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}