package education.entity;

public class Memo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memo.memoID
     *
     * @mbggenerated
     */
    private Integer memoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memo.studentID
     *
     * @mbggenerated
     */
    private String studentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memo.courseID
     *
     * @mbggenerated
     */
    private Integer courseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memo.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memo.memoID
     *
     * @return the value of memo.memoID
     *
     * @mbggenerated
     */
    public Integer getMemoid() {
        return memoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memo.memoID
     *
     * @param memoid the value for memo.memoID
     *
     * @mbggenerated
     */
    public void setMemoid(Integer memoid) {
        this.memoid = memoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memo.studentID
     *
     * @return the value of memo.studentID
     *
     * @mbggenerated
     */
    public String getStudentid() {
        return studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memo.studentID
     *
     * @param studentid the value for memo.studentID
     *
     * @mbggenerated
     */
    public void setStudentid(String studentid) {
        this.studentid = studentid == null ? null : studentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memo.courseID
     *
     * @return the value of memo.courseID
     *
     * @mbggenerated
     */
    public Integer getCourseid() {
        return courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memo.courseID
     *
     * @param courseid the value for memo.courseID
     *
     * @mbggenerated
     */
    public void setCourseid(Integer courseid) {
        this.courseid = courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memo.description
     *
     * @return the value of memo.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memo.description
     *
     * @param description the value for memo.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}