package education.entity;

public class Paper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.paperID
     *
     * @mbggenerated
     */
    private Integer paperid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.teacherID
     *
     * @mbggenerated
     */
    private Integer teacherid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.courseID
     *
     * @mbggenerated
     */
    private Integer courseid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.paperID
     *
     * @return the value of paper.paperID
     *
     * @mbggenerated
     */
    public Integer getPaperid() {
        return paperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.paperID
     *
     * @param paperid the value for paper.paperID
     *
     * @mbggenerated
     */
    public void setPaperid(Integer paperid) {
        this.paperid = paperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.teacherID
     *
     * @return the value of paper.teacherID
     *
     * @mbggenerated
     */
    public Integer getTeacherid() {
        return teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.teacherID
     *
     * @param teacherid the value for paper.teacherID
     *
     * @mbggenerated
     */
    public void setTeacherid(Integer teacherid) {
        this.teacherid = teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.courseID
     *
     * @return the value of paper.courseID
     *
     * @mbggenerated
     */
    public Integer getCourseid() {
        return courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.courseID
     *
     * @param courseid the value for paper.courseID
     *
     * @mbggenerated
     */
    public void setCourseid(Integer courseid) {
        this.courseid = courseid;
    }
}