package education.entity;

public class PaperExerciseKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paperexercise.exerciseID
     *
     * @mbggenerated
     */
    private Integer exerciseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paperexercise.paperID
     *
     * @mbggenerated
     */
    private Integer paperid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paperexercise.exerciseID
     *
     * @return the value of paperexercise.exerciseID
     *
     * @mbggenerated
     */
    public Integer getExerciseid() {
        return exerciseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paperexercise.exerciseID
     *
     * @param exerciseid the value for paperexercise.exerciseID
     *
     * @mbggenerated
     */
    public void setExerciseid(Integer exerciseid) {
        this.exerciseid = exerciseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paperexercise.paperID
     *
     * @return the value of paperexercise.paperID
     *
     * @mbggenerated
     */
    public Integer getPaperid() {
        return paperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paperexercise.paperID
     *
     * @param paperid the value for paperexercise.paperID
     *
     * @mbggenerated
     */
    public void setPaperid(Integer paperid) {
        this.paperid = paperid;
    }
}