package education.entity;

public class ProgressKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column progress.kpID
     *
     * @mbggenerated
     */
    private Integer kpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column progress.progressID
     *
     * @mbggenerated
     */
    private Integer progressid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column progress.kpID
     *
     * @return the value of progress.kpID
     *
     * @mbggenerated
     */
    public Integer getKpid() {
        return kpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column progress.kpID
     *
     * @param kpid the value for progress.kpID
     *
     * @mbggenerated
     */
    public void setKpid(Integer kpid) {
        this.kpid = kpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column progress.progressID
     *
     * @return the value of progress.progressID
     *
     * @mbggenerated
     */
    public Integer getProgressid() {
        return progressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column progress.progressID
     *
     * @param progressid the value for progress.progressID
     *
     * @mbggenerated
     */
    public void setProgressid(Integer progressid) {
        this.progressid = progressid;
    }
}