package education.entity;

public class Progress extends ProgressKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column progress.learn
     *
     * @mbggenerated
     */
    private Boolean learn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column progress.learn
     *
     * @return the value of progress.learn
     *
     * @mbggenerated
     */
    public Boolean getLearn() {
        return learn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column progress.learn
     *
     * @param learn the value for progress.learn
     *
     * @mbggenerated
     */
    public void setLearn(Boolean learn) {
        this.learn = learn;
    }
}